### ISSUE TITLE
Phoenix session error in Honeybadger.Plug

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#1]
I'm probably missing something obvious (first time using Phoenix), but I am getting the error "key :session not found in: %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}" when I try to add the plug to a vanilla controller:

https://github.com/honeybadger-io/crywolf-elixir/blob/master/web/controllers/page_controller.ex#L12

Is the issue that I need to manually configure the session in Phoenix first? I'd expect it to skip the session data if it can't access it gracefully.

**Comment by rbishop** [comment]
Phoenix has some manual setup you need to do to use sessions with regard to choosing the session store. I think right now it can use either `ets` tables or cookies as the session store. Here is a link to a page with more info:

http://www.phoenixframework.org/v0.6.2/docs/sessions

One other little oddity with sessions is that Plug first requires you to call `fetch_session` on the connection before you can access session data (I think is to avoid the expense of loading that data in the event that it isn't used). You're plugging the `fetch_session` function in your router so that should be taken care of for you though.

Thanks for pointing this out! I'll add some extra handling around Phoenix apps that haven't configured a session so they fail gracefully. Do you mind pasting a stacktrace here to help me cover this?

**Comment by joshuap** [comment]
@rbishop sure, here's the stacktrace:

```
        (crywolf) web/controllers/page_controller.ex:3: Crywolf.PageController.handle_errors/2
        (plug) lib/plug/error_handler.ex:94: Plug.ErrorHandler.__catch__/5
        (crywolf) lib/phoenix/router.ex:297: Crywolf.Router.dispatch/2
        (crywolf) lib/phoenix/router.ex:2: Crywolf.Router.call/2
        (crywolf) lib/crywolf/endpoint.ex:1: Crywolf.Endpoint.phoenix_endpoint_pipeline/1
        (crywolf) lib/plug/debugger.ex:90: Crywolf.Endpoint."call (overridable 3)"/2
        (crywolf) lib/phoenix/endpoint/render_errors.ex:34: Crywolf.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy_handler.ex:50: Phoenix.Endpoint.CowboyHandler.upgrade/4
```

**Comment by joshuap** [comment]
You should be able to reproduce this by pulling down that app and running the server and then navigate to "http://localhost:4000/runtime_error". I added the session config in 341b64977aebaf46befd03c8c5ef75dccba03088 but still get that error, so I'm thinking maybe it's not an issue that the session wasn't configured.

**Comment by rbishop** [comment]
This should be wokring now. Just make sure to grab the latest push:

`mix deps.update honeybadger`

I also cleaned up some things around how the "application" gets started and fixed a bug with some of the configuration defaults getting computed at compile-time. This caused functions like `System.cwd/0` and `System.get_env/1` to be the values of when the Honeybadger "application" was compiled rather than where it was ran.

application is in quotes because I'm referring to this: http://elixir-lang.org/docs/stable/elixir/Application.html

**Comment by rbishop** [comment]
Also make sure to add `:honeybadger` to the `applications` list in `mix.exs` so that the Honeybadger library is started automatically. I'll document all of this in a README later :)

**Comment by joshuap** [comment]
Sweet, that did it. Thanks!
