### ISSUE TITLE
UndefinedFunctionError: undefined function: :badarg.__struct__/0 (module :badarg is not available)

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#13]
We're having an error when parsing logs using the logfmt library:

https://github.com/jclem/logfmt-elixir/issues/6

When those errors happen, we also see the following in our logs, and the error is not reported (using the `use_logger` option):

```
01:02:03.208 [warn]  Unable to notify Honeybadger! UndefinedFunctionError: undefined function: :badarg.__struct__/0 (module :badarg is not available)
```

**Comment by rbishop** [comment]
I think I know the reason this is happening. `:badarg` is an Erlang exception rather than an Elixir exception so it does not have a `__struct__` where as all Elixir exceptions are `struct`s. On line 7 of `notice.ex` we try and get the struct of the exception and since `:badarg` doesn't have a struct it blows up.

One possible solution is to add some handling to Notice that checks if the module is an Elixir module or an Erlang module. One easy way to tell that is if we convert the module atom to a string all of the Elixir modules start with `Elixir.` e.g. `Elixir.UndefinedFunctionError` versus `:badarg`.

**Comment by rbishop** [comment]
There's something very meta about looking at code for turning exceptions back into exceptions in the exception handling code of an exception handling app.

**Comment by joshuap** [comment]
Heh, :+1:.

Thanks, that makes sense. I'll work up a PR for this (unless you're dying to take it). :)

**Comment by rbishop** [comment]
Have at it! If it is helpful:

Another observation I made is that Erlang exceptions are just atoms and not modules. So maybe an easy fix is to use try/catch on calling atom.module_info. If that blows up then you know it's an Erlang error atom and can handle it accordingly.
