### ISSUE TITLE
Honeybadger.notify/2 doesn't report context.

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#19]
@knewter noticed this while working on his ElixirSips screencast: `Honeybadger.notify(exception, context)` didn't report the local context with the error.

**Comment by muhmi** [comment]
:+1:

**Comment by muhmi** [comment]
How is this supposed to work?

Is it so that here 
https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger.ex#L138 
do_notify is supposed to get a map like `%{user_id: 12345, cookie: "monster"}`?

But does this https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/notice.ex#L17 mean that only things inside `:honeybadger_context`will be sent to the API?

Just curious and really would like to use this library =)

**Comment by joshuap** [comment]
This was discovered Friday evening; we'll be working on a fix this week. :) In the meantime, you can still feel free to use this library; this issue is not causing error reporting to break. The problem is that the context passed to `Honeybadger.notify/2` is not being sent to the api. What *should* happen is that the local context from `Honeybadger.notify/2` should be merged with any global context set by `Honeybadger.context/1` when constructing the notice.

**Comment by rbishop** [comment]
I think the issue is that Notice expects a Map with a `honeybadger_context` key. In the logger, you receive the crashed processeses (wut) entire process dictionary. I'm currentily grabbing the `honeybadger_context` key out of the process dictionary. This means later on Notice finds nothing at that key. Working on a fix now.

**Comment by joshuap** [comment]
@rbishop I'm thinking we can cut a new release of the library after #23 is merged. Does that sound right?

**Comment by rbishop** [comment]
Sounds good to me. I just realized I can simplify the testing and get rid of those `timer.sleep/1` calls. I'll try and set some time aside tonight to do that.

**Comment by joshuap** [comment]
:trophy:
