### ISSUE TITLE
[Feature] Add an option to define a fingerprint

### ISSUE THREAD

**Issue by axelson** [honeybadger-io/honeybadger-elixir#233]
The ruby library allows you to specify the `:fingerprint` which controls the grouping. It would be nice to be able to control the fingerprint in Elixir as well.

**Comment by stympy** [comment]
The documentation for the Rayburn client for sending additional info along with the error is [here](https://docs.honeybadger.io/lib/ruby/getting-started/reporting-errors.html#passing-additional-options-to-honeybadger-notify). My thought is that we can do something similar as a solution for this issue. What do you think, @joshuap?

**Comment by joshuap** [comment]
I think we could do something similar, although it may look different from Ruby. `Honeybadger.notify` in Elixir accepts an exact number of arguments, and I don't *believe* the API currently supports keyword arguments like we do in Ruby, such as `Honeybadger.notify(exception, fingerprint: 'string')`. Something like that might be a nice optimization if possible.

The other/additional way that we could support fingerprints in Elixir is to add a global config option which allows you to define a function that given a notice, returns the fingerprint for the notice (we have a similar option in Ruby, which uses a `Proc`).

I would say let's definitely add the global config, and also support the local/`Honeybadger.notify` option if feasible.

Any thoughts on the best implementation for this, @sorentwo?

**Comment by sorentwo** [comment]
#### Global Fingerprints

@joshuap Are you imagining that the top level function would replicate the [before_notice](https://docs.honeybadger.io/lib/ruby/getting-started/customizing-error-grouping.html#customizing-the-grouping-for-all-exceptions) behavior? Or, would it be more localized and just be a function to calculate the fingerprint? Are there any other use cases for the `before_notify` callback?

#### Localized Fingerprints

The top level `Honeybadger.notify` function has multiple arities. Due to default arguments for both `metadata` and `stacktrace` there are three functions defined:

1. `notify(exception)` -> `notify(exception, %{}, [])`
2. `notify(exception, context)` -> `notify(exception, context, [])`
3. `notify(exception, context, stacktrace)` -> `notify(exception, context, stacktrace)`.

The best implementation I can think of is to define a new clause for `notify/2` with a signature like:

```elixir
notify(exception :: Notice.noticeable(), options :: Keyword.t())
```

Here we would accept `context`, `stacktrace`, `fingerprint`, etc. as options. We can use guards to keep the old `notify/2` where the second argument is a map and add this new more compact clause.

An alternative, which I'm not really in favor of, is to define `notify/4` and accept the options as the fourth argument.

**Comment by stympy** [comment]
I vote for adding a copy of the before_notice behavior *and* adding the new `notify/2` as proposed. :)

**Comment by joshuap** [comment]
Are you imagining that the top-level function would replicate the before_notice behavior? Or, would it be more localized and just be a function to calculate the fingerprint? Are there any other use cases for the before_notify callback?

> I could go for either approach. I would prefer a more generic `before_notify` style callback if possible since it can be applied to a variety of use cases.

> The best implementation I can think of is to define a new clause for notify/2

Love that. 👍

**Comment by sorentwo** [comment]
Great. If somebody wants to pick this up I'm happy to advise and review. Otherwise, if nobody has claimed it before next week I can work on it.

**Comment by JediLuke** [comment]
Has there been any progress on this? Currently all our calls to `Honeybadger.notify/2` get wrapped in a RuntimeError, so they all get grouped together - which makes it hard to really figure out if you've seen an error before, how many times, etc.

**Comment by JediLuke** [comment]
Once this has been implemented, another great feature would be throttling the number of requests sent per a certain timeframe, based on their fingerprint. The way we have structured our application, a task may fail & be restarted. This an result in lots of honeybadgers for essentially the same error if the restart doesn't fix the problem.
