### ISSUE TITLE
HoneyBadger is always compiled with :prod environment

### ISSUE THREAD

**Issue by jonatandahora** [honeybadger-io/honeybadger-elixir#31]
Even if i set environment_name as :dev i get notified in compile-time exceptions as prod like @joshuap described in #8.
Once the app finishes compiling, it falls back to :dev.

**Comment by joshuap** [comment]
Thanks for reporting. We'll take a look.

**Comment by rbishop** [comment]
Does this happen when you use a tool like exrm or just using mix?

**Comment by jonatandahora** [comment]
@rbishop just with mix.

**Comment by rbishop** [comment]
This line appears to be the issue: https://github.com/honeybadger-io/honeybadger-elixir/blob/master/mix.exs#L21

For some reason, during compile time `Mix.env/0` always evaluates to `prod` when called in the Mixfile but when called in the project it has the right value. I'll open up an issue in the Mix project. For now I think we can fix this by doing something like:

`env: [environment_name: String.to_atom(System.get_env("MIX_ENV") || "dev")`

That's exactly what Mix itself does when establishing default state: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/state.ex#L11

**Comment by rbishop** [comment]
It turns out we can't do that proposed fix because an environment like `test` is set at runtime and not via an environment variable. The next best idea I have is to compare Mix.env in our application settings (earlier in the compilation) versus what it is now. If they don't match, prefer the setting of Mix.env now.

**Comment by rbishop** [comment]
Opened an issue here: https://github.com/elixir-lang/elixir/issues/4119

**Comment by joshuap** [comment]
@rbishop looks like it's up to use to come up with a solution to this since they won't change the behavior in Elixir. It sounds like our options are pretty limited:

1. We could remove the default `environment_name` and require it to be set in the user's project, or:
2. Leave the default and update our documentation to mention the compile-time difference, or:
3. Get the value some other way, like reading the `MIX_ENV` environment variable directly and providing our own default.

What do you guys think?

**Comment by joshuap** [comment]
Somehow I overlooked #33 while writing that last reply. I'm OK with that fix, although I think it would still be better if we could get the environment name transparently in a majority of cases. Would it be possible to read the default from the `MIX_ENV` environment variable and then fall back to the behavior in #33? Would that introduce any other issues, like where the mix env is set programmatically vs. via the environment variable?
