### ISSUE TITLE
Honeybadger for use in umbrella project

### ISSUE THREAD

**Issue by nauger** [honeybadger-io/honeybadger-elixir#59]
We've been using HB in our project for a few months with good success.  Our project has expanded  into an elixir umbrella, that basically has two Phoenix Endpoints running under the same beam/erlang process.

Is it possible to configure honeybadger to work with both apps at the same time?

Thoughts?

Thanks!

**Comment by joshuap** [comment]
Hi Nick, great to hear that Honeybadger has been working well for you so far. :)

I don't have any experience in trying this, honestly, so take what I say with a grain of salt. I'm thinking that you should be able to configure both of your Phoenix endpoints to use Honeybadger, but they would both report to the same Honeybadger project. I'm not sure if that would be a problem or not depending on how your apps are set up. We currently have the concept of your project being linked to a single OTP app, which we even have [a config option](https://github.com/honeybadger-io/honeybadger-elixir#advanced-configuration) for. We use the `:app` option to highlight which files in your stack traces belong to your project and which are from other vendors.

@nurugger07 may have some additional thoughts, but I'm thinking that basically this is something that you'll have to try out and see if you can make it work. It would be great if you could report your findings back here so that we can consider adding support for multiple apps or having an official recommendation for how to use the current lib in an umbrella project.

**Comment by mmmries** [comment]
I think it would work to configure your honeybadger key in the top-level `config/config.exs` and then have both phoenix apps depend on `honeybadger` and add it to their routers.

I have one phoenix app in my umbrella project and the reporting is working fine for me.
