### ISSUE TITLE
Refine controller/action reporting in Plug/Phoenix

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-elixir#72]
In Honeybadger we use the controller in our grouping algorithm. Currently we're using `__MODULE__` to determine the current controller in our `Plug`:

https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/plug.ex#L61

This works if you use the Plug inside each Phoenix controller. If you use the Plug inside the router, however (as many do), the router is reported instead of the controller.

The action is not currently reported at all, but should be.

**Comment by mwoods79** [comment]
Phoenix has had `controller_module\1` since at least version 1.0.  Using this might break the current plug, we will either need to be clever or have a separate plug for Phoenix specifically. Also, I'm not sure how far back we want to support? Phoenix 1.0 was released 2 years ago, it seems fine to drop support for older to me.

https://github.com/phoenixframework/phoenix/blob/v1.0.0/lib/phoenix/controller.ex#L141-L142
