### ISSUE TITLE
excluded envs not being excluded

### ISSUE THREAD

**Issue by jbhatab** [honeybadger-io/honeybadger-elixir#77]
I'm required to put in config for honeybadger in config/config.exs and I use my staging api key and set the env to dev and include dev in excluded envs. I'm still getting dev errors on my staging honeybadger dashboard.

```
  config :honeybadger,
  api_key: "xxxxxxxx",
  exclude_envs: [:test, :dev, :staging],
  environment_name: :dev
```

I'm on .6. You can see a screenshot of what I mean below. What I want is just no dev or staging bugs. 

<img width="800" alt="screen shot 2017-02-07 at 8 23 32 pm" src="https://cloud.githubusercontent.com/assets/2458718/22723505/e70e4c74-ed73-11e6-80d3-10150ddbe814.png">

**Comment by joshuap** [comment]
@jbhatab can you update to 0.6.2 just to make sure this isn't something that was fixed in a more recent version?

Also, do you know where this specific error is being reported from? The possible locations would be [manually](https://github.com/honeybadger-io/honeybadger-elixir#manual-reporting) (using `Honeybadger.notify`), [Plug](https://github.com/honeybadger-io/honeybadger-elixir#phoenix-and-plug), or the [process logger](https://github.com/honeybadger-io/honeybadger-elixir#logger).

**Comment by jbhatab** [comment]
I'll play with this later.

**Comment by jbhatab** [comment]
@joshuap seems i cant upgrade to .62 since it requires poison 3.0 which requires me to upgrade phoenix which I don't want to do quite yet. :(

Think a fix was made for this in .61 or .62?

**Comment by mwoods79** [comment]
@jbhatab the poison requirement is currently relaxed in master. AFAIK it is scheduled to be released in 0.7.0

In the mean time can you point to master and see if this is still a problem?

**Comment by mwoods79** [comment]
@jbhatab 0.6.3 was released last week. It has lessened the requirements for poison (0.7.0 is right around the corner). Please test and see if you are still getting this error.

**Comment by joshuap** [comment]
To close this, I'd like to verify that the "ignoring an additional environment" scenario works on the latest package version.

**Comment by joshuap** [comment]
Wondering if this could be related to #94.

**Comment by joshuap** [comment]
This should be fixed on master.
